// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_read.sql

package db

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT count(*)
FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLinkById = `-- name: GetLinkById :one
SELECT DISTINCT
    id,
    original_url,
    short_name,
    created_at
FROM links
WHERE id = $1
`

func (q *Queries) GetLinkById(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkById, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByshortName = `-- name: GetLinkByshortName :one
SELECT
    id,
    original_url,
    short_name,
    created_at
FROM links
WHERE short_name = $1
`

func (q *Queries) GetLinkByshortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByshortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT
    id,
    original_url,
    short_name,
    created_at
FROM links
ORDER BY id
LIMIT $2::bigint OFFSET $1::bigint
`

type GetLinksParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) GetLinks(ctx context.Context, arg GetLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinks, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
