// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_visits_write.sql

package db

import (
	"context"
)

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (
    link_id,
    ip,
    user_agent,
    referer,
    status
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, link_id, ip, user_agent, referer, status, created_at
`

type CreateLinkVisitParams struct {
	LinkID    int64  `json:"link_id"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	Referer   string `json:"referer"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
