// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_read.sql

package db

import (
	"context"
)

const getLinkByshortName = `-- name: GetLinkByshortName :one
SELECT
    id,
    original_url,
    short_name,
    created_at
FROM links
WHERE short_name = $1
`

func (q *Queries) GetLinkByshortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByshortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT
    id,
    original_url,
    short_name,
    created_at
FROM links
`

func (q *Queries) GetLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
