// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_visits_read.sql

package db

import (
	"context"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT count(*)
FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLinkVisits = `-- name: GetLinkVisits :many
SELECT
    id,
    link_id,
    ip,
    user_agent,
    referer,
    status,
    created_at
FROM link_visits
ORDER BY id
LIMIT $2::bigint OFFSET $1::bigint
`

type GetLinkVisitsParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) GetLinkVisits(ctx context.Context, arg GetLinkVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, getLinkVisits, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.IP,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
