// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountLinkVisits(ctx context.Context) (int64, error)
	CountLinks(ctx context.Context) (int64, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error)
	DeleteLink(ctx context.Context, id int64) (int64, error)
	GetLinkById(ctx context.Context, id int64) (Link, error)
	GetLinkByShortName(ctx context.Context, shortName string) (Link, error)
	GetLinkVisits(ctx context.Context, arg GetLinkVisitsParams) ([]LinkVisit, error)
	GetLinks(ctx context.Context, arg GetLinksParams) ([]Link, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
